#!/bin/sh

# Compile
sudo make re && sudo make clean
if [[ $? -ne 0 ]]
then
    echo "Error while compiling Kamoulox.."
    exit
fi
# Copy Kamoulox files to system
sudo cp -r base /bin/
sudo cp base/kml.xml /bin/base/
if [[ $? -ne 0 ]]
then
    echo "Error while installing Kamoulox."
    exit
fi
sudo cp kamoulox /bin/

echo "Kamoulox successfully installed!"

kamoulox