#!/bin/sh

# Compile
sudo make re && sudo make clean
if [[ $? -ne 0 ]]
then
    echo "Error while compiling Kamoulox.."
fi
# Copy Kamoulox files to system
sudo cp -r base/kml.xml /bin/
if [[ $? -ne 0 ]]
then
    echo "Error while installing Kamoulox."
fi
sudo cp kamoulox /bin/

# Enable motd (please update depending on your OS
sudo echo "" >> ~/.bash_profile
sudo echo "kamoulox" >> ~/.bash_profile
if [[ $? -ne 0 ]]
then
    echo "Error while installing Kamoulox."
fi
echo "Kamoulox successfully installed!"

kamoulox